# Generated by Django 3.2.24 on 2024-03-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_category_data(apps, schema_editor):
    Category = apps.get_model('taxiapp', 'Category')  # Replace 'yourappname' with your actual app name
    categories = ['Experience', 'Question', 'Concern', 'News', 'Other']  # Add your default categories here
    for cat in categories:
        Category.objects.create(name=cat)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_category_data),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
