# Generated by Django 5.0.2 on 2024-03-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20240324_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sticky',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.topic'),
        ),
    ]
